"""link extracted fields to extraction runs

Revision ID: 042fbe17e758
Revises: db6b91123361
Create Date: 2026-09-12 00:57:05.403676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '042fbe17e758'
down_revision: Union[str, Sequence[str], None] = 'db6b91123361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extracted_fields', sa.Column('extraction_run_id', sa.UUID(), nullable=True), schema='extraction')
    op.add_column('extracted_fields', sa.Column('source_ocr_run_id', sa.UUID(), nullable=True), schema='extraction')
    op.create_index(op.f('ix_extraction_extracted_fields_extraction_run_id'), 'extracted_fields', ['extraction_run_id'], unique=False, schema='extraction')
    op.create_index(op.f('ix_extraction_extracted_fields_source_ocr_run_id'), 'extracted_fields', ['source_ocr_run_id'], unique=False, schema='extraction')
    op.create_foreign_key(None, 'extracted_fields', 'ocr_runs', ['source_ocr_run_id'], ['id'], source_schema='extraction', referent_schema='extraction', ondelete='SET NULL')
    op.create_foreign_key(None, 'extracted_fields', 'extraction_runs', ['extraction_run_id'], ['id'], source_schema='extraction', referent_schema='extraction', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'extracted_fields', schema='extraction', type_='foreignkey')
    op.drop_constraint(None, 'extracted_fields', schema='extraction', type_='foreignkey')
    op.drop_index(op.f('ix_extraction_extracted_fields_source_ocr_run_id'), table_name='extracted_fields', schema='extraction')
    op.drop_index(op.f('ix_extraction_extracted_fields_extraction_run_id'), table_name='extracted_fields', schema='extraction')
    op.drop_column('extracted_fields', 'source_ocr_run_id', schema='extraction')
    op.drop_column('extracted_fields', 'extraction_run_id', schema='extraction')
    # ### end Alembic commands ###
