"""add field evidence

Revision ID: 34f54d7ff2d7
Revises: c6f71cd97863
Create Date: 2026-09-11 20:41:06.487260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34f54d7ff2d7'
down_revision: Union[str, Sequence[str], None] = 'c6f71cd97863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('extracted_field_id', sa.UUID(), nullable=False),
    sa.Column('ocr_block_id', sa.UUID(), nullable=False),
    sa.Column('evidence_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['extracted_field_id'], ['extraction.extracted_fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ocr_block_id'], ['extraction.ocr_blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='extraction'
    )
    op.create_index(op.f('ix_extraction_field_evidence_extracted_field_id'), 'field_evidence', ['extracted_field_id'], unique=False, schema='extraction')
    op.create_index(op.f('ix_extraction_field_evidence_ocr_block_id'), 'field_evidence', ['ocr_block_id'], unique=False, schema='extraction')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extraction_field_evidence_ocr_block_id'), table_name='field_evidence', schema='extraction')
    op.drop_index(op.f('ix_extraction_field_evidence_extracted_field_id'), table_name='field_evidence', schema='extraction')
    op.drop_table('field_evidence', schema='extraction')
    # ### end Alembic commands ###
