"""add extracted fields

Revision ID: c6f71cd97863
Revises: fe2b928b04e2
Create Date: 2026-09-11 20:31:10.609563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6f71cd97863'
down_revision: Union[str, Sequence[str], None] = 'fe2b928b04e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extracted_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_page_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(length=100), nullable=False),
    sa.Column('evidence_bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_page_id'], ['documents.document_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='extraction'
    )
    op.create_index(op.f('ix_extraction_extracted_fields_document_page_id'), 'extracted_fields', ['document_page_id'], unique=False, schema='extraction')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extraction_extracted_fields_document_page_id'), table_name='extracted_fields', schema='extraction')
    op.drop_table('extracted_fields', schema='extraction')
    # ### end Alembic commands ###
