"""add extraction run tracking

Revision ID: db6b91123361
Revises: efbd486c05ed
Create Date: 2026-09-12 00:54:28.875530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db6b91123361'
down_revision: Union[str, Sequence[str], None] = 'efbd486c05ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('source_ocr_run_id', sa.UUID(), nullable=True),
    sa.Column('engine', sa.String(length=100), nullable=False),
    sa.Column('engine_version', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', name='extraction_run_status', schema='extraction'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_ocr_run_id'], ['extraction.ocr_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='extraction'
    )
    op.create_index(op.f('ix_extraction_extraction_runs_document_id'), 'extraction_runs', ['document_id'], unique=False, schema='extraction')
    op.create_index(op.f('ix_extraction_extraction_runs_source_ocr_run_id'), 'extraction_runs', ['source_ocr_run_id'], unique=False, schema='extraction')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extraction_extraction_runs_source_ocr_run_id'), table_name='extraction_runs', schema='extraction')
    op.drop_index(op.f('ix_extraction_extraction_runs_document_id'), table_name='extraction_runs', schema='extraction')
    op.drop_table('extraction_runs', schema='extraction')
    # ### end Alembic commands ###
