"""add OCR blocks

Revision ID: fe2b928b04e2
Revises: a0863ab59e43
Create Date: 2026-09-11 20:25:29.636418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe2b928b04e2'
down_revision: Union[str, Sequence[str], None] = 'a0863ab59e43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ocr_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ocr_run_id', sa.UUID(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ocr_run_id'], ['extraction.ocr_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='extraction'
    )
    op.create_index(op.f('ix_extraction_ocr_blocks_ocr_run_id'), 'ocr_blocks', ['ocr_run_id'], unique=False, schema='extraction')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extraction_ocr_blocks_ocr_run_id'), table_name='ocr_blocks', schema='extraction')
    op.drop_table('ocr_blocks', schema='extraction')
    # ### end Alembic commands ###
